### PR TITLE
Add .gitignore and Send + Sync for Buffer

### LINKED ISSUE #39: Is it reasonable to make `SliceDeque` Send + Sync?
I can see these traits aren't automatically implemented, however I don't see a ton of compelling reason they couldn't be manually implemented.  I want to know what the library author thinks.

### PR DESCRIPTION
**Pull request by Xaeroxe**
Fixes #39 

After having reviewed the API for `Buffer`, it seems unlikely this implementation is incorrect.  Feel free to close this if adding this isn't possible though.

### CODE REVIEW

**Comment by Xaeroxe** [comment]
CI failures seem extraneous and unrelated to this PR.

**Comment by gnzlbg** [comment]
@Xaeroxe thanks for the PR.

> CI failures seem extraneous and unrelated to this PR.

The failures with `syscall unknown` have nothing to do with this PR, but the `SYSV=1` should be green. 

This needs some tests, e.g., create two dummy functions that require `Send` and `Sync` and pass them a `SliceDeque` to verify that it compiles.

You also need to add a comment on top of each impl explaining why they are safe. 

* For `Send` the `impl`s of buffer are safe because it is possible to free Send from a different thread, and probably other reasons (e.g. when the buffer is moved to a different thread no references of any kind into the buffer are live).

* For `Sync`, it would be because passing `&` of buffer to different threads doesn't let you perform any operation that mutates anything in the buffer. None of the buffers `&self` methods make use of interior mutability, so nothing requires internal synchronization, therefore this is safe. 

Maybe there are other reasons, I am not very knowledgeable of the unsafety related to `Send` and `Sync`.

**Comment by Xaeroxe** [comment]
@gnzlbg Fixed, should be ready for merge now.

**Comment by Xaeroxe** [comment]
Nightly compiler used in CI is off its rocker.  It says the `SliceDeque` doesn't use type `T` but it's right there inside the `buf` member variable as `Buffer<T>`.

**Comment by gnzlbg** [comment]
Hi @Xaeroxe sorry for the delay, I had a busy weekend. I'll try to review and get it to work tonight, latest tomorrow. Thanks for working on this!

**Comment by Xaeroxe** [comment]
Thanks @gnzlbg ! Btw since I don't have any breaking changes in this PR I was hoping it could be pushed to cargo once it's merged, I've already bumped the version number in this.

**Comment by gnzlbg** [comment]
Thanks @Xaeroxe, v0.1.9 is available on crates.io with this changes!

**Pull request merged**
